#!/usr/bin/env python3

import sys
import os.path

MODDIR = os.path.dirname(__file__)
sys.path.insert(0, MODDIR)

from myaptlib import DEBIndex


def print_score_table(score_board):
    for place, deb, score in score_board:
        print("{}. {}\t\t\t{}".format(place, deb, score))


def run():
    if len(sys.argv) != 2:
        print("Missing architecture. Please provide.")
        print("Usage: {} ARCH".format(sys.argv[0]))
        sys.exit(1)

    arch = sys.argv[1]
    debindex = DEBIndex(arch)
    top_debs = debindex.get_top_packages()
    print_score_table(top_debs)


if __name__ == '__main__':
    run()

